### PR TITLE
Set resource limits on all deployments

### LINKED ISSUE #56: Set resource limits on all deployments
Need to set some relatively sane resource limits on all deployments.

### PR DESCRIPTION
**Pull request by jhujasonw**
Fixes #56

### CODE REVIEW

**Comment by jhujasonw** [comment]
The limits set in here are based off a `kubectl -n test top po` on the running instance.  They are likely to need to be adjusted.  Adding @derekbelrose and @birkland  for review of the values.

**Comment by jhujasonw** [comment]
FWIW: Here is the top from kubectl:
```
NAME                            CPU(cores)   MEMORY(bytes)
activemq-6bdd66d7f6-rgtv8       2m           154Mi
alpaca-6bcf4cbc99-cw947         3m           439Mi
cantaloupe-9ff987b89-4zmg9      1m           171Mi
crayfits-8668fb856b-dkkbc       1m           36Mi
drupal-c76467fdd-mvwvw          2m           76Mi
fits-58b8d75d7b-x8nhw           2m           191Mi
homarus-85889847f5-pvwxs        1m           36Mi
houdini-688bd84fbb-vgx6b        1m           36Mi
hypercube-569b66c7dc-2q846      1m           36Mi
reverseproxy-84ffc587dd-dvv6w   4m           13Mi
solr-664d97b978-4ml69           6m           705Mi
```

**Review by derekbelrose — APPROVED** [review]
These look like sane starting values. They will almost assuredly need to be tweaked.

**Review by birkland — APPROVED** [review]
The values are probably way off what's needed, but that's TODO.  

I created two tickets that are necessary before we go into production, implied by this work:
https://github.com/jhu-idc/iDC-general/issues/382 (for finding resource limits)
https://github.com/jhu-idc/iDC-general/issues/381 (for enabling Java to automatically set heap size based on these limits)

**Pull request merged**
